openapi: 3.0.0
info:
  title: Compiler service
  version: 1.0.0

paths:
  /api/languages:
    get:
      summary: Get supported languages
      responses:
        '200':
          description: Compilation successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  languages:
                    type: string
  /api/compile:
    post:
      summary: Compile code in a specific language
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                language:
                  type: string
                  enum: [c, cpp]
              required:
                - language
      responses:
        '200':
          description: Compilation successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  output:
                    type: string
        '400':
          description: Invalid request
